apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730335278282:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-B1fJk00TbDtm
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::730335278282:user/Rupa
      username: Rupa    
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-07T04:07:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1147"
  uid: 1f734e16-716b-4397-bd4f-525112f43b21
